SE VC JÁ TIVER A TABELA CLIENTE E QUISER ATUALIZAR ELA PARA ADICIONAR A TABELA DE PLANO:


CREATE TABLE cliente (

    CLIENTEID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(40),
    CPF VARCHAR(14) UNIQUE,
    GENERO VARCHAR(8),
    PETS VARCHAR(10),
    NASCIMENTO VARCHAR(10),
    EMAIL VARCHAR(30) UNIQUE,
    SENHA VARCHAR(20),
    ENDERECO VARCHAR(200),
    TELEFONE VARCHAR(14),
    PLANO INT,
    FOREIGN KEY (PLANO) REFERENCES PLANOS (PLANOID)
);

CREATE TABLE pets (
    NOME VARCHAR(40),
    TUTOR INT,
    SEXO VARCHAR(50),
    IDADE VARCHAR(5),
    ESPECIE VARCHAR(30),
    RACA VARCHAR(30),
    PETID INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (TUTOR) REFERENCES cliente (CLIENTEID)
);

CREATE TABLE PLANOS (
    PLANOID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(40),
    PRECO DOUBLE
);

PLANOS
INSERT INTO PLANOS (PLANOID, NOME, PRECO) VALUES (1, 'Plano Básico', 40.00)