CREATE TABLE cliente (

    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(40),
    CPF VARCHAR(14) UNIQUE,
    GENERO VARCHAR(8),
    PETS VARCHAR(10),
    NASCIMENTO VARCHAR(10),
    EMAIL VARCHAR(30) UNIQUE,
    SENHA VARCHAR(20),
    ENDERECO VARCHAR(200),
    TELEFONE VARCHAR(14),
);

CREATE TABLE pets (
    NOME VARCHAR(40),
    TUTOR INT,
    SEXO VARCHAR(50),
    IDADE VARCHAR(5),
    ESPECIE VARCHAR(30),
    RACA VARCHAR(30),
    PETID INT AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (TUTOR) REFERENCES cliente (ID)
);
